### ISSUE TITLE
Simple Example?

### ISSUE THREAD

**Issue by jmrichardson** [telekom/HPOflow#93]
I don't understand how to use this package.  Could you provide a basic example?   I don't understand the import_structure and how it relates to importing the modules?  Thanks

**Comment by PhilipMay** [comment]
Hi @jmrichardson 
thanks for asking and your interest in HPOflow.

The doc page should give a good overview for the three main components: https://telekom.github.io/HPOflow/

For the OptunaMLflow component we made examples for usage here: https://telekom.github.io/HPOflow/doc/OptunaMLflow.html

If you have more specific questions feel free to ask. I will try to improve the documentation then. Otherwise please close this issue.

Thanks
Philip
